# Generated by Django 2.2.1 on 2019-05-08 15:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190508_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='product_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='tags',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='timeline',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
