# Generated by Django 2.2.1 on 2019-05-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190508_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='user',
        ),
    ]
