# Generated by Django 2.2.1 on 2019-05-10 16:14

import app.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_startup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Administrative Services'), (1, 'Advertising'), (2, 'Agriculture and Farming'), (3, 'Apps'), (4, 'Artificial Intelligence'), (5, 'Biotechnology'), (6, 'Clothing and Apparel'), (7, 'Commerce and Shopping'), (9, 'Community and Lifestyle'), (10, 'Consumer Electronics'), (11, 'Consumer Goods'), (12, 'Content and Publishing'), (13, 'Data and Analytics'), (14, 'Design'), (15, 'Education'), (16, 'Energy'), (17, 'Events'), (18, 'Financial Services'), (19, 'Food and Beverage'), (20, 'Gaming'), (21, 'Government and Military'), (22, 'Hardware'), (23, 'Health Care'), (24, 'Information Technology'), (25, 'Internet Services'), (26, 'Lending and Investments'), (27, 'Manufacturing'), (28, 'Media and Entertainment'), (29, 'Messaging and Telecommunications'), (30, 'Music and Audio'), (31, 'Mobile'), (32, 'Natural Resources'), (33, 'Navigation and Mapping'), (34, 'Payments'), (35, 'Platforms'), (36, 'Privacy and Security'), (37, 'Professional Services'), (38, 'Real Estate'), (39, 'Sales and Marketing'), (40, 'Science and Engineering'), (41, 'Software'), (42, 'Sports'), (43, 'Sustainability'), (44, 'Transportation'), (45, 'Travel and Tourism'), (46, 'Video')], default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=jsonfield.fields.JSONField(default=[], validators=[app.validators.validate_members]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='raiseAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='timeline',
            field=jsonfield.fields.JSONField(default=[], validators=[app.validators.validate_timeline]),
        ),
    ]
