# Generated by Django 2.2.1 on 2019-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190510_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='product_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
