# Generated by Django 2.2.1 on 2019-05-11 01:25

import app.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190510_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('query', models.CharField(default='', max_length=100)),
                ('category', models.PositiveSmallIntegerField(null=True)),
                ('topic', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='startup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Startup'),
        ),
        migrations.AddField(
            model_name='startup',
            name='pitching_video_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='startup',
            name='background',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='business_model',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='future',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='market',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[app.validators.validate_members]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='solution',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='timeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[app.validators.validate_timeline]),
        ),
    ]
