# Generated by Django 2.2.1 on 2019-05-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190511_1657'),
        ('app', '0006_auto_20190511_0125'),
    ]

    operations = [
    ]
