# Generated by Django 2.2.1 on 2019-05-13 00:53

import app.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_merge_20190512_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('reply_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_startups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='startup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='startup_feedbacks', to='app.Startup'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_likes', to='app.Startup'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='startup',
            name='background',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='business_model',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='future',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='market',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, validators=[app.validators.validate_members]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitching_video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='raiseAmount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='solution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='timeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, validators=[app.validators.validate_timeline]),
        ),
        migrations.AddField(
            model_name='reply',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to='app.Feedback'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
