# Generated by Django 2.2.1 on 2019-05-13 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190513_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_startups', to=settings.AUTH_USER_MODEL),
        ),
    ]
