# Generated by Django 2.2.1 on 2019-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190515_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='background',
            field=models.TextField(blank=True, default='', max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='business_model',
            field=models.TextField(blank=True, default='', max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='future',
            field=models.TextField(blank=True, default='', max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='market',
            field=models.TextField(blank=True, default='', max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='solution',
            field=models.TextField(blank=True, default='', max_length=200000, null=True),
        ),
    ]
